name: marvelous_carousel
description: Marvelous Carousel enables you to craft impressive sliders, carousels, and walkthrough sliders.
version: 0.0.13
homepage: https://github.com/kspo/marvelous_carousel.git

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

